// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Connection/Callback.h"
#include "Connection/DbConnectionBase.h"
#include "Connection/DbConnectionBuilder.h"
#include "Connection/Subscription.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Reducers/ApplyFoliageEdit.g.h"
#include "ModuleBindings/Reducers/ApplyVoxelEdit.g.h"
#include "ModuleBindings/Reducers/ClearFoliageEdit.g.h"
#include "ModuleBindings/Reducers/ClearVoxelEdit.g.h"
#include "ModuleBindings/Reducers/SetWorldConfig.g.h"
#include "ModuleBindings/Reducers/UpdatePlayerPosition.g.h"
#include "Types/Builtins.h"
#include "SpacetimeDBClient.g.generated.h"

// Forward declarations
class UDbConnection;
class URemoteTables;
class URemoteReducers;
class URemoteProcedures;
class USubscriptionBuilder;
class USubscriptionHandle;

/** Forward declaration for tables */
class UFoliageEditTable;
class UPlayerPositionTable;
class UPlayerSessionTable;
class UVoxelEditTable;
class UWorldConfigTable;
/***/

// Delegates using the generated connection type. These wrap the base
// delegates defined in the SDK so that projects can work directly with
// UDbConnection without manual casting in user code.
DECLARE_DYNAMIC_DELEGATE_ThreeParams(
	FOnConnectDelegate,
	UDbConnection*, Connection,
	FSpacetimeDBIdentity, Identity,
	const FString&, Token);

DECLARE_DYNAMIC_DELEGATE_TwoParams(
	FOnDisconnectDelegate,
	UDbConnection*, Connection,
	const FString&, Error);


// Context classes for event handling

USTRUCT(BlueprintType)
struct ORAKAI_API FContextBase
{
	GENERATED_BODY()

	FContextBase() : Db(nullptr), Reducers(nullptr), Procedures(nullptr), Conn(nullptr) {};
	FContextBase(UDbConnection* InConn);

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteTables* Db;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteReducers* Reducers;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteProcedures* Procedures;

	bool IsActive() const;
	void Disconnect();
	bool TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const;
	FSpacetimeDBConnectionId GetConnectionId() const;
	USubscriptionBuilder* SubscriptionBuilder();

protected:
	UPROPERTY()
	UDbConnection* Conn;

};

UCLASS()
class ORAKAI_API UContextBaseBpLib : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

private:
	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteTables* GetDb(const FContextBase& Ctx) { return Ctx.Db; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteReducers* GetReducers(const FContextBase& Ctx) { return Ctx.Reducers; }

	static URemoteProcedures* GetProcedures(const FContextBase& Ctx) { return Ctx.Procedures; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static bool IsActive(const FContextBase& Ctx) { return Ctx.IsActive(); }
};

UENUM(BlueprintType, Category = "SpacetimeDB")
enum class EReducerTag : uint8
{
    ApplyFoliageEdit,
    ApplyVoxelEdit,
    ClearFoliageEdit,
    ClearVoxelEdit,
    SetWorldConfig,
    UpdatePlayerPosition
};

USTRUCT(BlueprintType)
struct ORAKAI_API FReducer
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    EReducerTag Tag = static_cast<EReducerTag>(0);

    TVariant<FApplyFoliageEditArgs, FApplyVoxelEditArgs, FClearFoliageEditArgs, FClearVoxelEditArgs, FSetWorldConfigArgs, FUpdatePlayerPositionArgs> Data;

    // Optional metadata
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    FString ReducerName;
    uint32 ReducerId = 0;
    uint32 RequestId = 0;

    static FReducer ApplyFoliageEdit(const FApplyFoliageEditArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::ApplyFoliageEdit;
        Out.Data.Set<FApplyFoliageEditArgs>(Value);
        Out.ReducerName = TEXT("apply_foliage_edit");
        return Out;
    }

    FORCEINLINE bool IsApplyFoliageEdit() const { return Tag == EReducerTag::ApplyFoliageEdit; }
    FORCEINLINE FApplyFoliageEditArgs GetAsApplyFoliageEdit() const
    {
        ensureMsgf(IsApplyFoliageEdit(), TEXT("Reducer does not hold ApplyFoliageEdit!"));
        return Data.Get<FApplyFoliageEditArgs>();
    }

    static FReducer ApplyVoxelEdit(const FApplyVoxelEditArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::ApplyVoxelEdit;
        Out.Data.Set<FApplyVoxelEditArgs>(Value);
        Out.ReducerName = TEXT("apply_voxel_edit");
        return Out;
    }

    FORCEINLINE bool IsApplyVoxelEdit() const { return Tag == EReducerTag::ApplyVoxelEdit; }
    FORCEINLINE FApplyVoxelEditArgs GetAsApplyVoxelEdit() const
    {
        ensureMsgf(IsApplyVoxelEdit(), TEXT("Reducer does not hold ApplyVoxelEdit!"));
        return Data.Get<FApplyVoxelEditArgs>();
    }

    static FReducer ClearFoliageEdit(const FClearFoliageEditArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::ClearFoliageEdit;
        Out.Data.Set<FClearFoliageEditArgs>(Value);
        Out.ReducerName = TEXT("clear_foliage_edit");
        return Out;
    }

    FORCEINLINE bool IsClearFoliageEdit() const { return Tag == EReducerTag::ClearFoliageEdit; }
    FORCEINLINE FClearFoliageEditArgs GetAsClearFoliageEdit() const
    {
        ensureMsgf(IsClearFoliageEdit(), TEXT("Reducer does not hold ClearFoliageEdit!"));
        return Data.Get<FClearFoliageEditArgs>();
    }

    static FReducer ClearVoxelEdit(const FClearVoxelEditArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::ClearVoxelEdit;
        Out.Data.Set<FClearVoxelEditArgs>(Value);
        Out.ReducerName = TEXT("clear_voxel_edit");
        return Out;
    }

    FORCEINLINE bool IsClearVoxelEdit() const { return Tag == EReducerTag::ClearVoxelEdit; }
    FORCEINLINE FClearVoxelEditArgs GetAsClearVoxelEdit() const
    {
        ensureMsgf(IsClearVoxelEdit(), TEXT("Reducer does not hold ClearVoxelEdit!"));
        return Data.Get<FClearVoxelEditArgs>();
    }

    static FReducer SetWorldConfig(const FSetWorldConfigArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::SetWorldConfig;
        Out.Data.Set<FSetWorldConfigArgs>(Value);
        Out.ReducerName = TEXT("set_world_config");
        return Out;
    }

    FORCEINLINE bool IsSetWorldConfig() const { return Tag == EReducerTag::SetWorldConfig; }
    FORCEINLINE FSetWorldConfigArgs GetAsSetWorldConfig() const
    {
        ensureMsgf(IsSetWorldConfig(), TEXT("Reducer does not hold SetWorldConfig!"));
        return Data.Get<FSetWorldConfigArgs>();
    }

    static FReducer UpdatePlayerPosition(const FUpdatePlayerPositionArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::UpdatePlayerPosition;
        Out.Data.Set<FUpdatePlayerPositionArgs>(Value);
        Out.ReducerName = TEXT("update_player_position");
        return Out;
    }

    FORCEINLINE bool IsUpdatePlayerPosition() const { return Tag == EReducerTag::UpdatePlayerPosition; }
    FORCEINLINE FUpdatePlayerPositionArgs GetAsUpdatePlayerPosition() const
    {
        ensureMsgf(IsUpdatePlayerPosition(), TEXT("Reducer does not hold UpdatePlayerPosition!"));
        return Data.Get<FUpdatePlayerPositionArgs>();
    }

    FORCEINLINE bool operator==(const FReducer& Other) const
    {
        if (Tag != Other.Tag || ReducerId != Other.ReducerId || RequestId != Other.RequestId || ReducerName != Other.ReducerName) return false;
        switch (Tag)
        {
        case EReducerTag::ApplyFoliageEdit:
            return GetAsApplyFoliageEdit() == Other.GetAsApplyFoliageEdit();
        case EReducerTag::ApplyVoxelEdit:
            return GetAsApplyVoxelEdit() == Other.GetAsApplyVoxelEdit();
        case EReducerTag::ClearFoliageEdit:
            return GetAsClearFoliageEdit() == Other.GetAsClearFoliageEdit();
        case EReducerTag::ClearVoxelEdit:
            return GetAsClearVoxelEdit() == Other.GetAsClearVoxelEdit();
        case EReducerTag::SetWorldConfig:
            return GetAsSetWorldConfig() == Other.GetAsSetWorldConfig();
        case EReducerTag::UpdatePlayerPosition:
            return GetAsUpdatePlayerPosition() == Other.GetAsUpdatePlayerPosition();
        default: return false;
        }
    }
    FORCEINLINE bool operator!=(const FReducer& Other) const { return !(*this == Other); }
};

UCLASS()
class ORAKAI_API UReducerBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer ApplyFoliageEdit(const FApplyFoliageEditArgs& Value) {
        return FReducer::ApplyFoliageEdit(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsApplyFoliageEdit(const FReducer& Reducer) { return Reducer.IsApplyFoliageEdit(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FApplyFoliageEditArgs GetAsApplyFoliageEdit(const FReducer& Reducer) {
        return Reducer.GetAsApplyFoliageEdit();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer ApplyVoxelEdit(const FApplyVoxelEditArgs& Value) {
        return FReducer::ApplyVoxelEdit(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsApplyVoxelEdit(const FReducer& Reducer) { return Reducer.IsApplyVoxelEdit(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FApplyVoxelEditArgs GetAsApplyVoxelEdit(const FReducer& Reducer) {
        return Reducer.GetAsApplyVoxelEdit();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer ClearFoliageEdit(const FClearFoliageEditArgs& Value) {
        return FReducer::ClearFoliageEdit(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsClearFoliageEdit(const FReducer& Reducer) { return Reducer.IsClearFoliageEdit(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FClearFoliageEditArgs GetAsClearFoliageEdit(const FReducer& Reducer) {
        return Reducer.GetAsClearFoliageEdit();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer ClearVoxelEdit(const FClearVoxelEditArgs& Value) {
        return FReducer::ClearVoxelEdit(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsClearVoxelEdit(const FReducer& Reducer) { return Reducer.IsClearVoxelEdit(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FClearVoxelEditArgs GetAsClearVoxelEdit(const FReducer& Reducer) {
        return Reducer.GetAsClearVoxelEdit();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer SetWorldConfig(const FSetWorldConfigArgs& Value) {
        return FReducer::SetWorldConfig(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsSetWorldConfig(const FReducer& Reducer) { return Reducer.IsSetWorldConfig(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FSetWorldConfigArgs GetAsSetWorldConfig(const FReducer& Reducer) {
        return Reducer.GetAsSetWorldConfig();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer UpdatePlayerPosition(const FUpdatePlayerPositionArgs& Value) {
        return FReducer::UpdatePlayerPosition(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsUpdatePlayerPosition(const FReducer& Reducer) { return Reducer.IsUpdatePlayerPosition(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FUpdatePlayerPositionArgs GetAsUpdatePlayerPosition(const FReducer& Reducer) {
        return Reducer.GetAsUpdatePlayerPosition();
    }
};

/** Metadata describing a reducer run. */
USTRUCT(BlueprintType)
struct ORAKAI_API FOrakaiReducerEvent
{
	GENERATED_BODY()

	/** Timestamp for when the reducer executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the reducer */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBIdentity CallerIdentity;

	/** Connection ID for the caller */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBConnectionId CallerConnectionId;

	/** Energy consumed while executing */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FEnergyQuantaType EnergyConsumed;

	/** Detailed call information */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FReducer Reducer;

	FORCEINLINE bool operator==(const FOrakaiReducerEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp && CallerIdentity == Other.CallerIdentity &&
			CallerConnectionId == Other.CallerConnectionId && EnergyConsumed == Other.EnergyConsumed &&
			Reducer == Other.Reducer;
	}

	FORCEINLINE bool operator!=(const FOrakaiReducerEvent& Other) const
	{
		return !(*this == Other);
	}
};

// No procedures defined in this module.
/** Metadata describing a procedure run. */
USTRUCT(BlueprintType)
struct ORAKAI_API FOrakaiProcedureEvent
{
	GENERATED_BODY()

	/** Timestamp for when the procedure executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the procedure */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBProcedureStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimeDuration TotalHostExecutionDuration;

	FOrakaiProcedureEvent() {
	}
	FOrakaiProcedureEvent(FProcedureEvent Event) {
		Timestamp = Event.Timestamp;
		Status = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
		TotalHostExecutionDuration = Event.TotalHostExecutionDuration;
	}
	FORCEINLINE bool operator==(const FOrakaiProcedureEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp &&
			TotalHostExecutionDuration == Other.TotalHostExecutionDuration;
	}

	FORCEINLINE bool operator!=(const FOrakaiProcedureEvent& Other) const
	{
		return !(*this == Other);
	}
};

/** Represents event with variant message data. */
USTRUCT(BlueprintType)
struct ORAKAI_API FOrakaiEvent
{
	GENERATED_BODY()

	/** Tagged union holding reducer call, unit events, or error string */
	TVariant<FReducer, FSpacetimeDBUnit, FString> MessageData;

	/** Type tag indicating what this event represents */
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	ESpacetimeDBEventTag Tag = ESpacetimeDBEventTag::UnknownTransaction;

	/** === Static factory methods ===*/
	static FOrakaiEvent Reducer(const FReducer& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::Reducer;
		Obj.MessageData.Set<FReducer>(Value);
		return Obj;
	}

	static FOrakaiEvent SubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FOrakaiEvent UnsubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnsubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FOrakaiEvent Disconnected(const FSpacetimeDBUnit& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::Disconnected;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FOrakaiEvent Transaction(const FSpacetimeDBUnit& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::Transaction;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FOrakaiEvent SubscribeError(const FString& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeError;
		Obj.MessageData.Set<FString>(Value);
		return Obj;
	}

	static FOrakaiEvent UnknownTransaction(const FSpacetimeDBUnit& Value)
	{
		FOrakaiEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnknownTransaction;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	FORCEINLINE bool IsReducer() const { return Tag == ESpacetimeDBEventTag::Reducer; }
	FORCEINLINE FReducer GetAsReducer() const
	{
		ensureMsgf(IsReducer(), TEXT("MessageData does not hold Reducer!"));
		return MessageData.Get<FReducer>();
	}

	FORCEINLINE bool IsSubscribeApplied() const { return Tag == ESpacetimeDBEventTag::SubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsSubscribeApplied() const
	{
		ensureMsgf(IsSubscribeApplied(), TEXT("MessageData does not hold SubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsUnsubscribeApplied() const { return Tag == ESpacetimeDBEventTag::UnsubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnsubscribeApplied() const
	{
		ensureMsgf(IsUnsubscribeApplied(), TEXT("MessageData does not hold UnsubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsDisconnected() const { return Tag == ESpacetimeDBEventTag::Disconnected; }
	FORCEINLINE FSpacetimeDBUnit GetAsDisconnected() const
	{
		ensureMsgf(IsDisconnected(), TEXT("MessageData does not hold Disconnected!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsTransaction() const { return Tag == ESpacetimeDBEventTag::Transaction; }
	FORCEINLINE FSpacetimeDBUnit GetAsTransaction() const
	{
		ensureMsgf(IsTransaction(), TEXT("MessageData does not hold Transaction!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsSubscribeError() const { return Tag == ESpacetimeDBEventTag::SubscribeError; }
	FORCEINLINE FString GetAsSubscribeError() const
	{
		ensureMsgf(IsSubscribeError(), TEXT("MessageData does not hold SubscribeError!"));
		return MessageData.Get<FString>();
	}

	FORCEINLINE bool IsUnknownTransaction() const { return Tag == ESpacetimeDBEventTag::UnknownTransaction; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnknownTransaction() const
	{
		ensureMsgf(IsUnknownTransaction(), TEXT("MessageData does not hold UnknownTransaction!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool operator==(const FOrakaiEvent& Other) const
	{
		if (Tag != Other.Tag) return false;
		switch (Tag)
		{
		case ESpacetimeDBEventTag::Reducer: return GetAsReducer() == Other.GetAsReducer();
		case ESpacetimeDBEventTag::SubscribeApplied: return GetAsSubscribeApplied() == Other.GetAsSubscribeApplied();
		case ESpacetimeDBEventTag::UnsubscribeApplied: return GetAsUnsubscribeApplied() == Other.GetAsUnsubscribeApplied();
		case ESpacetimeDBEventTag::Disconnected: return GetAsDisconnected() == Other.GetAsDisconnected();
		case ESpacetimeDBEventTag::Transaction: return GetAsTransaction() == Other.GetAsTransaction();
		case ESpacetimeDBEventTag::SubscribeError: return GetAsSubscribeError() == Other.GetAsSubscribeError();
		case ESpacetimeDBEventTag::UnknownTransaction: return GetAsUnknownTransaction() == Other.GetAsUnknownTransaction();
		default: return false;
		}
	}

	FORCEINLINE bool operator!=(const FOrakaiEvent& Other) const
	{
		return !(*this == Other);
	}
};

UCLASS()
class ORAKAI_API UOrakaiEventBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent Reducer(const FReducer& InValue)
    {
        return FOrakaiEvent::Reducer(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent SubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FOrakaiEvent::SubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent UnsubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FOrakaiEvent::UnsubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent Disconnected(const FSpacetimeDBUnit& InValue)
    {
        return FOrakaiEvent::Disconnected(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent Transaction(const FSpacetimeDBUnit& InValue)
    {
        return FOrakaiEvent::Transaction(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent SubscribeError(const FString& InValue)
    {
        return FOrakaiEvent::SubscribeError(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|OrakaiEvent")
    static FOrakaiEvent UnknownTransaction(const FSpacetimeDBUnit& InValue)
    {
        return FOrakaiEvent::UnknownTransaction(InValue);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsReducer(const FOrakaiEvent& Event) { return Event.IsReducer(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsSubscribeApplied(const FOrakaiEvent& Event) { return Event.IsSubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsUnsubscribeApplied(const FOrakaiEvent& Event) { return Event.IsUnsubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsDisconnected(const FOrakaiEvent& Event) { return Event.IsDisconnected(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsTransaction(const FOrakaiEvent& Event) { return Event.IsTransaction(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsSubscribeError(const FOrakaiEvent& Event) { return Event.IsSubscribeError(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static bool IsUnknownTransaction(const FOrakaiEvent& Event) { return Event.IsUnknownTransaction(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FReducer GetAsReducer(const FOrakaiEvent& Event)
    {
        return Event.GetAsReducer();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FSpacetimeDBUnit GetAsSubscribeApplied(const FOrakaiEvent& Event)
    {
        return Event.GetAsSubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FSpacetimeDBUnit GetAsUnsubscribeApplied(const FOrakaiEvent& Event)
    {
        return Event.GetAsUnsubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FSpacetimeDBUnit GetAsDisconnected(const FOrakaiEvent& Event)
    {
        return Event.GetAsDisconnected();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FSpacetimeDBUnit GetAsTransaction(const FOrakaiEvent& Event)
    {
        return Event.GetAsTransaction();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FString GetAsSubscribeError(const FOrakaiEvent& Event)
    {
        return Event.GetAsSubscribeError();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|OrakaiEvent")
    static FSpacetimeDBUnit GetAsUnknownTransaction(const FOrakaiEvent& Event)
    {
        return Event.GetAsUnknownTransaction();
    }

};


USTRUCT(BlueprintType)
struct ORAKAI_API FEventContext : public FContextBase
{
	GENERATED_BODY()

	FEventContext() = default;
	FEventContext(UDbConnection* InConn, const FOrakaiEvent& InEvent) : FContextBase(InConn), Event(InEvent) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FOrakaiEvent Event;
};

USTRUCT(BlueprintType)
struct ORAKAI_API FReducerEventContext : public FContextBase
{
	GENERATED_BODY()

	FReducerEventContext() = default;
	FReducerEventContext(UDbConnection* InConn, FOrakaiReducerEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FOrakaiReducerEvent Event;
};

USTRUCT(BlueprintType)
struct ORAKAI_API FProcedureEventContext : public FContextBase
{
	GENERATED_BODY()

	FProcedureEventContext() = default;
	FProcedureEventContext(UDbConnection* InConn, FOrakaiProcedureEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FOrakaiProcedureEvent Event;
};

USTRUCT(BlueprintType)
struct ORAKAI_API FErrorContext : public FContextBase
{
	GENERATED_BODY()

	FErrorContext() = default;
	FErrorContext(UDbConnection* InConn, const FString& InError) : FContextBase(InConn), Error(InError) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FString Error;

};

USTRUCT(BlueprintType)
struct ORAKAI_API FSubscriptionEventContext : public FContextBase
{
	GENERATED_BODY()

	FSubscriptionEventContext() = default;
	FSubscriptionEventContext(UDbConnection* InConn) : FContextBase(InConn) {}

};

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionApplied,
	FSubscriptionEventContext, Context);

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionError,
	FErrorContext, Context);

// RemoteTables class
UCLASS(BlueprintType)
class ORAKAI_API URemoteTables : public UObject
{
    GENERATED_BODY()

public:
    void Initialize();

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UFoliageEditTable* FoliageEdit;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UPlayerPositionTable* PlayerPosition;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UPlayerSessionTable* PlayerSession;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UVoxelEditTable* VoxelEdit;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UWorldConfigTable* WorldConfig;

};

// RemoteReducers class
UCLASS(BlueprintType)
class ORAKAI_API URemoteReducers : public UObject
{
    GENERATED_BODY()

public:

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_EightParams(
        FApplyFoliageEditHandler,
        const FReducerEventContext&, Context,
        int32, WorldX,
        int32, WorldY,
        int32, WorldZ,
        bool, Removed,
        int32, TypeId,
        float, Yaw,
        float, Scale
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FApplyFoliageEditHandler OnApplyFoliageEdit;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void ApplyFoliageEdit(const int32 WorldX, const int32 WorldY, const int32 WorldZ, const bool Removed, const int32 TypeId, const float Yaw, const float Scale);

    bool InvokeApplyFoliageEdit(const FReducerEventContext& Context, const UApplyFoliageEditReducer* Args);
    bool InvokeApplyFoliageEditWithArgs(const FReducerEventContext& Context, const FApplyFoliageEditArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_NineParams(
        FApplyVoxelEditHandler,
        const FReducerEventContext&, Context,
        int32, ChunkX,
        int32, ChunkY,
        int32, ChunkZ,
        int32, LocalX,
        int32, LocalY,
        int32, LocalZ,
        int32, MaterialId,
        bool, IsWater
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FApplyVoxelEditHandler OnApplyVoxelEdit;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void ApplyVoxelEdit(const int32 ChunkX, const int32 ChunkY, const int32 ChunkZ, const int32 LocalX, const int32 LocalY, const int32 LocalZ, const int32 MaterialId, const bool IsWater);

    bool InvokeApplyVoxelEdit(const FReducerEventContext& Context, const UApplyVoxelEditReducer* Args);
    bool InvokeApplyVoxelEditWithArgs(const FReducerEventContext& Context, const FApplyVoxelEditArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(
        FClearFoliageEditHandler,
        const FReducerEventContext&, Context,
        int32, WorldX,
        int32, WorldY,
        int32, WorldZ
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FClearFoliageEditHandler OnClearFoliageEdit;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void ClearFoliageEdit(const int32 WorldX, const int32 WorldY, const int32 WorldZ);

    bool InvokeClearFoliageEdit(const FReducerEventContext& Context, const UClearFoliageEditReducer* Args);
    bool InvokeClearFoliageEditWithArgs(const FReducerEventContext& Context, const FClearFoliageEditArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_SevenParams(
        FClearVoxelEditHandler,
        const FReducerEventContext&, Context,
        int32, ChunkX,
        int32, ChunkY,
        int32, ChunkZ,
        int32, LocalX,
        int32, LocalY,
        int32, LocalZ
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FClearVoxelEditHandler OnClearVoxelEdit;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void ClearVoxelEdit(const int32 ChunkX, const int32 ChunkY, const int32 ChunkZ, const int32 LocalX, const int32 LocalY, const int32 LocalZ);

    bool InvokeClearVoxelEdit(const FReducerEventContext& Context, const UClearVoxelEditReducer* Args);
    bool InvokeClearVoxelEditWithArgs(const FReducerEventContext& Context, const FClearVoxelEditArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(
        FSetWorldConfigHandler,
        const FReducerEventContext&, Context,
        int64, WorldSeed,
        uint32, GenerationVersion
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FSetWorldConfigHandler OnSetWorldConfig;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void SetWorldConfig(const int64 WorldSeed, const uint32 GenerationVersion);

    bool InvokeSetWorldConfig(const FReducerEventContext& Context, const USetWorldConfigReducer* Args);
    bool InvokeSetWorldConfigWithArgs(const FReducerEventContext& Context, const FSetWorldConfigArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams(
        FUpdatePlayerPositionHandler,
        const FReducerEventContext&, Context,
        double, X,
        double, Y,
        double, Z,
        float, Yaw,
        float, Pitch
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FUpdatePlayerPositionHandler OnUpdatePlayerPosition;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void UpdatePlayerPosition(const double X, const double Y, const double Z, const float Yaw, const float Pitch);

    bool InvokeUpdatePlayerPosition(const FReducerEventContext& Context, const UUpdatePlayerPositionReducer* Args);
    bool InvokeUpdatePlayerPositionWithArgs(const FReducerEventContext& Context, const FUpdatePlayerPositionArgs& Args);

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledReducerError InternalOnUnhandledReducerError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;
};

// RemoteProcedures class
UCLASS(BlueprintType)
class ORAKAI_API URemoteProcedures : public UObject
{
    GENERATED_BODY()

public:

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledProcedureError InternalOnUnhandledProcedureError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;
};

// SubscriptionBuilder class
UCLASS(BlueprintType)
class ORAKAI_API USubscriptionBuilder : public USubscriptionBuilderBase
{
    GENERATED_BODY()

public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnApplied(FOnSubscriptionApplied Callback);

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnError(FOnSubscriptionError Callback);

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionHandle* Subscribe(const TArray<FString>& SQL);

    /** Convenience for subscribing to all rows from all tables */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionHandle* SubscribeToAllTables();


    friend class UDbConnection;
    friend class UDbConnectionBase;

protected:
    UPROPERTY()
    class UDbConnection* Conn;

    // Delegates stored so Subscribe() can bind forwarding callbacks
    FOnSubscriptionApplied OnAppliedDelegateInternal;
    FOnSubscriptionError OnErrorDelegateInternal;
};

// SubscriptionHandle class
UCLASS(BlueprintType)
class ORAKAI_API USubscriptionHandle : public USubscriptionHandleBase
{
    GENERATED_BODY()

public:

    USubscriptionHandle() {};

    explicit USubscriptionHandle(UDbConnection* InConn);

    friend class USubscriptionBuilder;

private:
    UPROPERTY()
    class UDbConnection* Conn;

    // Delegates that expose subscription events with connection aware contexts
    FOnSubscriptionApplied OnAppliedDelegate;
    FOnSubscriptionError OnErrorDelegate;

    UFUNCTION()
    void ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx);

    UFUNCTION()
    void ForwardOnError(const FErrorContextBase& BaseCtx);
};

/*
    @Note: Child class of UDbConnectionBuilderBase.
*/
UCLASS(BlueprintType)
class ORAKAI_API UDbConnectionBuilder : public UDbConnectionBuilderBase
{
    GENERATED_BODY()
public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithUri(const FString& InUri);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithDatabaseName(const FString& InName);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithToken(const FString& InToken);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithCompression(const ESpacetimeDBCompression& InCompression);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnect(FOnConnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnectError(FOnConnectErrorDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnDisconnect(FOnDisconnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnection* Build();

private:

    // Stored delegates which will be forwarded when the connection events occur.
    FOnConnectDelegate OnConnectDelegateInternal;
    FOnDisconnectDelegate OnDisconnectDelegateInternal;
};

// Main DbConnection class
UCLASS(BlueprintType)
class ORAKAI_API UDbConnection : public UDbConnectionBase
{
    GENERATED_BODY()

public:
    explicit UDbConnection(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());


    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteProcedures* Procedures;

    // Delegates that allow users to bind with the concrete connection type.
    FOnConnectDelegate OnConnectDelegate;
    FOnDisconnectDelegate OnDisconnectDelegate;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

    /** Static entry point for constructing a connection. */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB", DisplayName = "SpacetimeDB Orakai Builder")
    static UDbConnectionBuilder* Builder();

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledReducerError OnUnhandledReducerError;

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledProcedureError OnUnhandledProcedureError;


protected:

    // Hook up error handling to reducers and procedures
    virtual void PostInitProperties() override;

    UFUNCTION()
    void ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken);
    UFUNCTION()
    void ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error);

    UFUNCTION()
    void OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error);

    UFUNCTION()
    void OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error);

    // Override the DbConnectionBase methods to handle updates and events
    virtual void DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event) override;
    
    // Override the reducer event handler to dispatch events to the appropriate reducers
    virtual void ReducerEvent(const FReducerEvent& Event) override;
    
    // Override the reducer event failed handler
    virtual void ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage) override;
    // Override the procedure event failed handler
    virtual void ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage) override;

    friend class USubscriptionBuilder;
    friend class UDbConnectionBuilder;
    friend class URemoteReducers;

    // Internal reducer correlation helpers (request_id -> typed reducer)
    void RegisterPendingTypedReducer(uint32 RequestId, FReducer Reducer);
    bool TryGetPendingTypedReducer(uint32 RequestId, FReducer& OutReducer) const;
    bool TryTakePendingTypedReducer(uint32 RequestId, FReducer& OutReducer);

private:
    TMap<uint32, FReducer> PendingTypedReducers;
};

