// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/SpacetimeDBClient.g.h"
#include "DBCache/WithBsatn.h"
#include "BSATN/UEBSATNHelpers.h"
#include "ModuleBindings/Tables/FoliageEditTable.g.h"
#include "ModuleBindings/Tables/PlayerPositionTable.g.h"
#include "ModuleBindings/Tables/PlayerSessionTable.g.h"
#include "ModuleBindings/Tables/VoxelEditTable.g.h"
#include "ModuleBindings/Tables/WorldConfigTable.g.h"

UDbConnection::UDbConnection(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer)
{
	Db = ObjectInitializer.CreateDefaultSubobject<URemoteTables>(this, TEXT("RemoteTables"));
	Db->Initialize();
	
	Reducers = ObjectInitializer.CreateDefaultSubobject<URemoteReducers>(this, TEXT("RemoteReducers"));
	Reducers->Conn = this;

	Procedures = ObjectInitializer.CreateDefaultSubobject<URemoteProcedures>(this, TEXT("RemoteProcedures"));
	Procedures->Conn = this;

	RegisterTable<FFoliageEditType, UFoliageEditTable, FEventContext>(TEXT("foliage_edit"), Db->FoliageEdit);
	RegisterTable<FPlayerPositionType, UPlayerPositionTable, FEventContext>(TEXT("player_position"), Db->PlayerPosition);
	RegisterTable<FPlayerSessionType, UPlayerSessionTable, FEventContext>(TEXT("player_session"), Db->PlayerSession);
	RegisterTable<FVoxelEditType, UVoxelEditTable, FEventContext>(TEXT("voxel_edit"), Db->VoxelEdit);
	RegisterTable<FWorldConfigType, UWorldConfigTable, FEventContext>(TEXT("world_config"), Db->WorldConfig);
}

FContextBase::FContextBase(UDbConnection* InConn)
{
	Db = InConn->Db;
	Reducers = InConn->Reducers;
	Procedures = InConn->Procedures;
	Conn = InConn;
}
bool FContextBase::IsActive() const
{
	return Conn->IsActive();
}
void FContextBase::Disconnect()
{
	Conn->Disconnect();
}
USubscriptionBuilder* FContextBase::SubscriptionBuilder()
{
	return Conn->SubscriptionBuilder();
}
bool FContextBase::TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const
{
	return Conn->TryGetIdentity(OutIdentity);
}
FSpacetimeDBConnectionId FContextBase::GetConnectionId() const
{
	return Conn->GetConnectionId();
}

void URemoteTables::Initialize()
{

	/** Creating tables */
	FoliageEdit = NewObject<UFoliageEditTable>(this);
	PlayerPosition = NewObject<UPlayerPositionTable>(this);
	PlayerSession = NewObject<UPlayerSessionTable>(this);
	VoxelEdit = NewObject<UVoxelEditTable>(this);
	WorldConfig = NewObject<UWorldConfigTable>(this);
	/**/

	/** Initialization */
	FoliageEdit->PostInitialize();
	PlayerPosition->PostInitialize();
	PlayerSession->PostInitialize();
	VoxelEdit->PostInitialize();
	WorldConfig->PostInitialize();
	/**/
}

void URemoteReducers::ApplyFoliageEdit(const int32 WorldX, const int32 WorldY, const int32 WorldZ, const bool Removed, const int32 TypeId, const float Yaw, const float Scale)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FApplyFoliageEditArgs ReducerArgs(WorldX, WorldY, WorldZ, Removed, TypeId, Yaw, Scale);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("apply_foliage_edit"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::ApplyFoliageEdit(ReducerArgs)); }
}

bool URemoteReducers::InvokeApplyFoliageEdit(const FReducerEventContext& Context, const UApplyFoliageEditReducer* Args)
{
    if (!OnApplyFoliageEdit.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ApplyFoliageEdit"));
        }
        return false;
    }

    OnApplyFoliageEdit.Broadcast(Context, Args->WorldX, Args->WorldY, Args->WorldZ, Args->Removed, Args->TypeId, Args->Yaw, Args->Scale);
    return true;
}

bool URemoteReducers::InvokeApplyFoliageEditWithArgs(const FReducerEventContext& Context, const FApplyFoliageEditArgs& Args)
{
    if (!OnApplyFoliageEdit.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ApplyFoliageEdit"));
        }
        return false;
    }

    OnApplyFoliageEdit.Broadcast(Context, Args.WorldX, Args.WorldY, Args.WorldZ, Args.Removed, Args.TypeId, Args.Yaw, Args.Scale);
    return true;
}

void URemoteReducers::ApplyVoxelEdit(const int32 ChunkX, const int32 ChunkY, const int32 ChunkZ, const int32 LocalX, const int32 LocalY, const int32 LocalZ, const int32 MaterialId, const bool IsWater)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FApplyVoxelEditArgs ReducerArgs(ChunkX, ChunkY, ChunkZ, LocalX, LocalY, LocalZ, MaterialId, IsWater);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("apply_voxel_edit"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::ApplyVoxelEdit(ReducerArgs)); }
}

bool URemoteReducers::InvokeApplyVoxelEdit(const FReducerEventContext& Context, const UApplyVoxelEditReducer* Args)
{
    if (!OnApplyVoxelEdit.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ApplyVoxelEdit"));
        }
        return false;
    }

    OnApplyVoxelEdit.Broadcast(Context, Args->ChunkX, Args->ChunkY, Args->ChunkZ, Args->LocalX, Args->LocalY, Args->LocalZ, Args->MaterialId, Args->IsWater);
    return true;
}

bool URemoteReducers::InvokeApplyVoxelEditWithArgs(const FReducerEventContext& Context, const FApplyVoxelEditArgs& Args)
{
    if (!OnApplyVoxelEdit.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ApplyVoxelEdit"));
        }
        return false;
    }

    OnApplyVoxelEdit.Broadcast(Context, Args.ChunkX, Args.ChunkY, Args.ChunkZ, Args.LocalX, Args.LocalY, Args.LocalZ, Args.MaterialId, Args.IsWater);
    return true;
}

void URemoteReducers::ClearFoliageEdit(const int32 WorldX, const int32 WorldY, const int32 WorldZ)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FClearFoliageEditArgs ReducerArgs(WorldX, WorldY, WorldZ);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("clear_foliage_edit"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::ClearFoliageEdit(ReducerArgs)); }
}

bool URemoteReducers::InvokeClearFoliageEdit(const FReducerEventContext& Context, const UClearFoliageEditReducer* Args)
{
    if (!OnClearFoliageEdit.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearFoliageEdit"));
        }
        return false;
    }

    OnClearFoliageEdit.Broadcast(Context, Args->WorldX, Args->WorldY, Args->WorldZ);
    return true;
}

bool URemoteReducers::InvokeClearFoliageEditWithArgs(const FReducerEventContext& Context, const FClearFoliageEditArgs& Args)
{
    if (!OnClearFoliageEdit.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearFoliageEdit"));
        }
        return false;
    }

    OnClearFoliageEdit.Broadcast(Context, Args.WorldX, Args.WorldY, Args.WorldZ);
    return true;
}

void URemoteReducers::ClearVoxelEdit(const int32 ChunkX, const int32 ChunkY, const int32 ChunkZ, const int32 LocalX, const int32 LocalY, const int32 LocalZ)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FClearVoxelEditArgs ReducerArgs(ChunkX, ChunkY, ChunkZ, LocalX, LocalY, LocalZ);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("clear_voxel_edit"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::ClearVoxelEdit(ReducerArgs)); }
}

bool URemoteReducers::InvokeClearVoxelEdit(const FReducerEventContext& Context, const UClearVoxelEditReducer* Args)
{
    if (!OnClearVoxelEdit.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearVoxelEdit"));
        }
        return false;
    }

    OnClearVoxelEdit.Broadcast(Context, Args->ChunkX, Args->ChunkY, Args->ChunkZ, Args->LocalX, Args->LocalY, Args->LocalZ);
    return true;
}

bool URemoteReducers::InvokeClearVoxelEditWithArgs(const FReducerEventContext& Context, const FClearVoxelEditArgs& Args)
{
    if (!OnClearVoxelEdit.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearVoxelEdit"));
        }
        return false;
    }

    OnClearVoxelEdit.Broadcast(Context, Args.ChunkX, Args.ChunkY, Args.ChunkZ, Args.LocalX, Args.LocalY, Args.LocalZ);
    return true;
}

void URemoteReducers::SetWorldConfig(const int64 WorldSeed, const uint32 GenerationVersion)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FSetWorldConfigArgs ReducerArgs(WorldSeed, GenerationVersion);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("set_world_config"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::SetWorldConfig(ReducerArgs)); }
}

bool URemoteReducers::InvokeSetWorldConfig(const FReducerEventContext& Context, const USetWorldConfigReducer* Args)
{
    if (!OnSetWorldConfig.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SetWorldConfig"));
        }
        return false;
    }

    OnSetWorldConfig.Broadcast(Context, Args->WorldSeed, Args->GenerationVersion);
    return true;
}

bool URemoteReducers::InvokeSetWorldConfigWithArgs(const FReducerEventContext& Context, const FSetWorldConfigArgs& Args)
{
    if (!OnSetWorldConfig.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SetWorldConfig"));
        }
        return false;
    }

    OnSetWorldConfig.Broadcast(Context, Args.WorldSeed, Args.GenerationVersion);
    return true;
}

void URemoteReducers::UpdatePlayerPosition(const double X, const double Y, const double Z, const float Yaw, const float Pitch)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	FUpdatePlayerPositionArgs ReducerArgs(X, Y, Z, Yaw, Pitch);
	const uint32 RequestId = Conn->CallReducerTyped(TEXT("update_player_position"), ReducerArgs);
	if (RequestId != 0) { Conn->RegisterPendingTypedReducer(RequestId, FReducer::UpdatePlayerPosition(ReducerArgs)); }
}

bool URemoteReducers::InvokeUpdatePlayerPosition(const FReducerEventContext& Context, const UUpdatePlayerPositionReducer* Args)
{
    if (!OnUpdatePlayerPosition.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for UpdatePlayerPosition"));
        }
        return false;
    }

    OnUpdatePlayerPosition.Broadcast(Context, Args->X, Args->Y, Args->Z, Args->Yaw, Args->Pitch);
    return true;
}

bool URemoteReducers::InvokeUpdatePlayerPositionWithArgs(const FReducerEventContext& Context, const FUpdatePlayerPositionArgs& Args)
{
    if (!OnUpdatePlayerPosition.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for UpdatePlayerPosition"));
        }
        return false;
    }

    OnUpdatePlayerPosition.Broadcast(Context, Args.X, Args.Y, Args.Z, Args.Yaw, Args.Pitch);
    return true;
}

void UDbConnection::PostInitProperties()
{
    Super::PostInitProperties();
    
    // Connect OnUnhandledReducerError to Reducers.InternalOnUnhandledReducerError
    if (Reducers)
    {
        Reducers->InternalOnUnhandledReducerError.AddDynamic(this, &UDbConnection::OnUnhandledReducerErrorHandler);
    }

    // Connect OnUnhandledProcedureError to Procedures.InternalOnUnhandledProcedureError
    if (Procedures)
    {
        Procedures->InternalOnUnhandledProcedureError.AddDynamic(this, &UDbConnection::OnUnhandledProcedureErrorHandler);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error)
{
    if (OnUnhandledReducerError.IsBound())
    {
        OnUnhandledReducerError.Broadcast(Context, Error);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error)
{
    if (OnUnhandledProcedureError.IsBound())
    {
        OnUnhandledProcedureError.Broadcast(Context, Error);
    }
}

void UDbConnection::RegisterPendingTypedReducer(uint32 RequestId, FReducer Reducer)
{
    Reducer.RequestId = RequestId;
    PendingTypedReducers.Add(RequestId, MoveTemp(Reducer));
}

bool UDbConnection::TryGetPendingTypedReducer(uint32 RequestId, FReducer& OutReducer) const
{
    if (const FReducer* Found = PendingTypedReducers.Find(RequestId))
    {
        OutReducer = *Found;
        return true;
    }
    return false;
}

bool UDbConnection::TryTakePendingTypedReducer(uint32 RequestId, FReducer& OutReducer)
{
    if (FReducer* Found = PendingTypedReducers.Find(RequestId))
    {
        OutReducer = *Found;
        PendingTypedReducers.Remove(RequestId);
        return true;
    }
    return false;
}

void UDbConnection::ReducerEvent(const FReducerEvent& Event)
{
    if (!Reducers) { return; }

    FReducer DecodedReducer;
    if (!TryTakePendingTypedReducer(Event.RequestId, DecodedReducer))
    {
        const FString ErrorMessage = FString::Printf(TEXT("Reducer result for unknown request_id %u"), Event.RequestId);
        HandleProtocolViolation(ErrorMessage);
        return;
    }

    FOrakaiReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;
    ReducerEvent.Reducer            = DecodedReducer;

    FReducerEventContext Context(this, ReducerEvent);

    // Dispatch by typed reducer metadata
    const FString& ReducerName = ReducerEvent.Reducer.ReducerName;

    if (ReducerName == TEXT("apply_foliage_edit"))
    {
        FApplyFoliageEditArgs Args = ReducerEvent.Reducer.GetAsApplyFoliageEdit();
        Reducers->InvokeApplyFoliageEditWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("apply_voxel_edit"))
    {
        FApplyVoxelEditArgs Args = ReducerEvent.Reducer.GetAsApplyVoxelEdit();
        Reducers->InvokeApplyVoxelEditWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("clear_foliage_edit"))
    {
        FClearFoliageEditArgs Args = ReducerEvent.Reducer.GetAsClearFoliageEdit();
        Reducers->InvokeClearFoliageEditWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("clear_voxel_edit"))
    {
        FClearVoxelEditArgs Args = ReducerEvent.Reducer.GetAsClearVoxelEdit();
        Reducers->InvokeClearVoxelEditWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("set_world_config"))
    {
        FSetWorldConfigArgs Args = ReducerEvent.Reducer.GetAsSetWorldConfig();
        Reducers->InvokeSetWorldConfigWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("update_player_position"))
    {
        FUpdatePlayerPositionArgs Args = ReducerEvent.Reducer.GetAsUpdatePlayerPosition();
        Reducers->InvokeUpdatePlayerPositionWithArgs(Context, Args);
        return;
    }

    UE_LOG(LogTemp, Warning, TEXT("Unknown reducer: %s"), *ReducerName);
}

void UDbConnection::ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage)
{
    if (!Reducers) { return; }

    FOrakaiReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;

    FReducerEventContext Context(this, ReducerEvent);

    if (Reducers->InternalOnUnhandledReducerError.IsBound())
    {
        Reducers->InternalOnUnhandledReducerError.Broadcast(Context, ErrorMessage);
    }
}

void UDbConnection::ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage)
{
    if (!Procedures) { return; }

    FOrakaiProcedureEvent ProcedureEvent;
    ProcedureEvent.Status             = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
    ProcedureEvent.Timestamp          = Event.Timestamp;

    FProcedureEventContext Context(this, ProcedureEvent);

    if (Procedures->InternalOnUnhandledProcedureError.IsBound())
    {
        Procedures->InternalOnUnhandledProcedureError.Broadcast(Context, ErrorMessage);
    }
}

UDbConnectionBuilder* UDbConnection::Builder()
{
	return NewObject<UDbConnectionBuilder>();
}
// Added for creating subscriptions
USubscriptionBuilder* UDbConnection::SubscriptionBuilder()
{
	USubscriptionBuilder* Builder = NewObject<USubscriptionBuilder>(this);
	Builder->Conn = this;
	return Builder;
}
USubscriptionBuilder* USubscriptionBuilder::OnApplied(FOnSubscriptionApplied Callback)
{
	OnAppliedDelegateInternal = Callback;
	return this;
}
USubscriptionBuilder* USubscriptionBuilder::OnError(FOnSubscriptionError Callback)
{
	OnErrorDelegateInternal = Callback;
	return this;
}
USubscriptionHandle* USubscriptionBuilder::Subscribe(const TArray<FString>& SQL)
{
	USubscriptionHandle* Handle = NewObject<USubscriptionHandle>();

	// Store user callbacks on the handle
	Handle->Conn = Conn;
	Handle->OnAppliedDelegate = OnAppliedDelegateInternal;
	Handle->OnErrorDelegate = OnErrorDelegateInternal;

	// Bind forwarding functions that will convert base contexts
	FSubscriptionEventDelegate BaseApplied;
	BaseApplied.BindUFunction(Handle, TEXT("ForwardOnApplied"));
	OnAppliedBase(BaseApplied);

	FSubscriptionErrorDelegate BaseError;
	BaseError.BindUFunction(Handle, TEXT("ForwardOnError"));
	OnErrorBase(BaseError);

	SubscribeBase(SQL, Handle);
	if (Conn)
	{
		Conn->StartSubscription(Handle);
	}
	return Handle;
}
USubscriptionHandle* USubscriptionBuilder::SubscribeToAllTables()
{
	return Subscribe({ "SELECT * FROM * " });
}

USubscriptionHandle::USubscriptionHandle(UDbConnection* InConn)
{
	Conn = InConn;
}

void USubscriptionHandle::ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx)
{
	if (OnAppliedDelegate.IsBound())
	{
		FSubscriptionEventContext Ctx(Conn);
		OnAppliedDelegate.Execute(Ctx);
	}
}

void USubscriptionHandle::ForwardOnError(const FErrorContextBase& BaseCtx)
{
	if (OnErrorDelegate.IsBound())
	{
		FErrorContext Ctx(Conn, BaseCtx.Error);
		OnErrorDelegate.Execute(Ctx);
	}
}


// Cast from parent to child class
UDbConnectionBuilder* UDbConnectionBuilder::WithUri(const FString& InUri)
{
	return Cast<UDbConnectionBuilder>(WithUriBase(InUri));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithDatabaseName(const FString& InName)
{
	return Cast<UDbConnectionBuilder>(WithDatabaseNameBase(InName));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithToken(const FString& InToken)
{
	return Cast<UDbConnectionBuilder>(WithTokenBase(InToken));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithCompression(const ESpacetimeDBCompression& InCompression)
{
	return Cast<UDbConnectionBuilder>(WithCompressionBase(InCompression));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnect(FOnConnectDelegate Callback)
{
	OnConnectDelegateInternal = Callback;
	return this;
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnectError(FOnConnectErrorDelegate Callback)
{
	return Cast<UDbConnectionBuilder>(OnConnectErrorBase(Callback));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnDisconnect(FOnDisconnectDelegate Callback)
{
	OnDisconnectDelegateInternal = Callback;
	return this;
}
UDbConnection* UDbConnectionBuilder::Build()
{
	UDbConnection* Connection = NewObject<UDbConnection>();

	// Store delegates on the connection for later use
	Connection->OnConnectDelegate = OnConnectDelegateInternal;
	Connection->OnDisconnectDelegate = OnDisconnectDelegateInternal;

	// Wrap delegates so the base builder can bind them
	FOnConnectBaseDelegate BaseConnect;
	BaseConnect.BindUFunction(Connection, TEXT("ForwardOnConnect"));
	Connection->SetOnConnectDelegate(BaseConnect);
	OnConnectBase(BaseConnect);

	FOnDisconnectBaseDelegate BaseDisconnect;
	BaseDisconnect.BindUFunction(Connection, TEXT("ForwardOnDisconnect"));
	Connection->SetOnDisconnectDelegate(BaseDisconnect);
	OnDisconnectBase(BaseDisconnect);

	return Cast<UDbConnection>(BuildConnection(Connection));
}
void UDbConnection::ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken)
{
	if (OnConnectDelegate.IsBound())
	{
		OnConnectDelegate.Execute(this, Identity, Token);
	}
}
void UDbConnection::ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error)
{
	PendingTypedReducers.Empty();
	if (OnDisconnectDelegate.IsBound())
	{
		OnDisconnectDelegate.Execute(this, Error);
	}
}


void UDbConnection::DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event)
{
    FOrakaiEvent BaseEvent;
    BaseEvent.Tag = Event.Tag;

    switch (Event.Tag)
    {
    case ESpacetimeDBEventTag::Reducer:
    {
        FReducerEvent ReducerEvent = Event.GetAsReducer();
        FReducer Reducer;
        if (!TryGetPendingTypedReducer(ReducerEvent.RequestId, Reducer))
        {
            const FString ErrorMessage = FString::Printf(TEXT("Reducer result for unknown request_id %u"), ReducerEvent.RequestId);
            HandleProtocolViolation(ErrorMessage);
            return;
        }
        BaseEvent = FOrakaiEvent::Reducer(Reducer);
        break;
    }

    case ESpacetimeDBEventTag::SubscribeApplied:
        BaseEvent = FOrakaiEvent::SubscribeApplied(Event.GetAsSubscribeApplied());
        break;

    case ESpacetimeDBEventTag::UnsubscribeApplied:
        BaseEvent = FOrakaiEvent::UnsubscribeApplied(Event.GetAsUnsubscribeApplied());
        break;

    case ESpacetimeDBEventTag::Disconnected:
        BaseEvent = FOrakaiEvent::Disconnected(Event.GetAsDisconnected());
        break;

    case ESpacetimeDBEventTag::Transaction:
        BaseEvent = FOrakaiEvent::Transaction(Event.GetAsTransaction());
        break;

    case ESpacetimeDBEventTag::SubscribeError:
        BaseEvent = FOrakaiEvent::SubscribeError(Event.GetAsSubscribeError());
        break;

    case ESpacetimeDBEventTag::UnknownTransaction:
        BaseEvent = FOrakaiEvent::UnknownTransaction(Event.GetAsUnknownTransaction());
        break;

    default:
        break;
    }

    FEventContext Context(this, BaseEvent);
    // Populate typed reducer args for convenience in table handlers

    ApplyRegisteredTableUpdates(Update, &Context);
}

