// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "FoliageEditType.g.generated.h"

USTRUCT(BlueprintType)
struct ORAKAI_API FFoliageEditType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Key;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int64 ChunkKey = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 WorldX = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 WorldY = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 WorldZ = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool Removed = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 TypeId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Yaw = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Scale = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity EditedBy;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp EditedAt;

    FORCEINLINE bool operator==(const FFoliageEditType& Other) const
    {
        return Key == Other.Key && ChunkKey == Other.ChunkKey && WorldX == Other.WorldX && WorldY == Other.WorldY && WorldZ == Other.WorldZ && Removed == Other.Removed && TypeId == Other.TypeId && Yaw == Other.Yaw && Scale == Other.Scale && EditedBy == Other.EditedBy && EditedAt == Other.EditedAt;
    }

    FORCEINLINE bool operator!=(const FFoliageEditType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FFoliageEditType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param FoliageEditType The FFoliageEditType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FFoliageEditType& FoliageEditType)
{
    uint32 Hash = GetTypeHash(FoliageEditType.Key);
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.ChunkKey));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.WorldX));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.WorldY));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.WorldZ));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.Removed));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.TypeId));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.Yaw));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.Scale));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.EditedBy));
    Hash = HashCombine(Hash, GetTypeHash(FoliageEditType.EditedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FFoliageEditType);

    UE_SPACETIMEDB_STRUCT(FFoliageEditType, Key, ChunkKey, WorldX, WorldY, WorldZ, Removed, TypeId, Yaw, Scale, EditedBy, EditedAt);
}
