// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "PlayerSessionType.g.generated.h"

USTRUCT(BlueprintType)
struct ORAKAI_API FPlayerSessionType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Player;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool Online = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastSeen;

    FORCEINLINE bool operator==(const FPlayerSessionType& Other) const
    {
        return Player == Other.Player && Online == Other.Online && LastSeen == Other.LastSeen;
    }

    FORCEINLINE bool operator!=(const FPlayerSessionType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPlayerSessionType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PlayerSessionType The FPlayerSessionType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPlayerSessionType& PlayerSessionType)
{
    uint32 Hash = GetTypeHash(PlayerSessionType.Player);
    Hash = HashCombine(Hash, GetTypeHash(PlayerSessionType.Online));
    Hash = HashCombine(Hash, GetTypeHash(PlayerSessionType.LastSeen));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPlayerSessionType);

    UE_SPACETIMEDB_STRUCT(FPlayerSessionType, Player, Online, LastSeen);
}
