// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "PlayerPositionType.g.generated.h"

USTRUCT(BlueprintType)
struct ORAKAI_API FPlayerPositionType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Player;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double X = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Y = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Z = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Yaw = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Pitch = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp UpdatedAt;

    FORCEINLINE bool operator==(const FPlayerPositionType& Other) const
    {
        return Player == Other.Player && X == Other.X && Y == Other.Y && Z == Other.Z && Yaw == Other.Yaw && Pitch == Other.Pitch && UpdatedAt == Other.UpdatedAt;
    }

    FORCEINLINE bool operator!=(const FPlayerPositionType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPlayerPositionType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PlayerPositionType The FPlayerPositionType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPlayerPositionType& PlayerPositionType)
{
    uint32 Hash = GetTypeHash(PlayerPositionType.Player);
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.X));
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.Y));
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.Z));
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.Yaw));
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.Pitch));
    Hash = HashCombine(Hash, GetTypeHash(PlayerPositionType.UpdatedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPlayerPositionType);

    UE_SPACETIMEDB_STRUCT(FPlayerPositionType, Player, X, Y, Z, Yaw, Pitch, UpdatedAt);
}
