// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "VoxelEditType.g.generated.h"

USTRUCT(BlueprintType)
struct ORAKAI_API FVoxelEditType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Key;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int64 ChunkKey = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ChunkX = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ChunkY = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ChunkZ = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 LocalX = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 LocalY = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 LocalZ = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 MaterialId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool IsWater = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity EditedBy;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp EditedAt;

    FORCEINLINE bool operator==(const FVoxelEditType& Other) const
    {
        return Key == Other.Key && ChunkKey == Other.ChunkKey && ChunkX == Other.ChunkX && ChunkY == Other.ChunkY && ChunkZ == Other.ChunkZ && LocalX == Other.LocalX && LocalY == Other.LocalY && LocalZ == Other.LocalZ && MaterialId == Other.MaterialId && IsWater == Other.IsWater && EditedBy == Other.EditedBy && EditedAt == Other.EditedAt;
    }

    FORCEINLINE bool operator!=(const FVoxelEditType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FVoxelEditType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param VoxelEditType The FVoxelEditType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FVoxelEditType& VoxelEditType)
{
    uint32 Hash = GetTypeHash(VoxelEditType.Key);
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.ChunkKey));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.ChunkX));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.ChunkY));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.ChunkZ));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.LocalX));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.LocalY));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.LocalZ));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.MaterialId));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.IsWater));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.EditedBy));
    Hash = HashCombine(Hash, GetTypeHash(VoxelEditType.EditedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FVoxelEditType);

    UE_SPACETIMEDB_STRUCT(FVoxelEditType, Key, ChunkKey, ChunkX, ChunkY, ChunkZ, LocalX, LocalY, LocalZ, MaterialId, IsWater, EditedBy, EditedAt);
}
