// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "WorldConfigType.g.generated.h"

USTRUCT(BlueprintType)
struct ORAKAI_API FWorldConfigType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int64 WorldSeed = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 GenerationVersion = 0;

    FORCEINLINE bool operator==(const FWorldConfigType& Other) const
    {
        return Id == Other.Id && WorldSeed == Other.WorldSeed && GenerationVersion == Other.GenerationVersion;
    }

    FORCEINLINE bool operator!=(const FWorldConfigType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FWorldConfigType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param WorldConfigType The FWorldConfigType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FWorldConfigType& WorldConfigType)
{
    uint32 Hash = GetTypeHash(WorldConfigType.Id);
    Hash = HashCombine(Hash, GetTypeHash(WorldConfigType.WorldSeed));
    Hash = HashCombine(Hash, GetTypeHash(WorldConfigType.GenerationVersion));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FWorldConfigType);

    UE_SPACETIMEDB_STRUCT(FWorldConfigType, Id, WorldSeed, GenerationVersion);
}
