// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/FoliageEditType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "FoliageEditTable.g.generated.h"

UCLASS(Blueprintable)
class UFoliageEditChunkKeyIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FFoliageEditType> Filter(const int64& ChunkKey) const
    {
        TArray<FFoliageEditType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<int64>>(
            OutResults,
            TEXT("ChunkKey"),
            MakeTuple(ChunkKey)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FFoliageEditType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    UFUNCTION(BlueprintCallable)
    void FilterChunkKey(TArray<FFoliageEditType>& OutResults, const int64& ChunkKey)
    {
        OutResults = Filter(ChunkKey);
    }

    TSharedPtr<FTableCache<FFoliageEditType>> LocalCache;
};

UCLASS(Blueprintable)
class ORAKAI_API UFoliageEditKeyUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FFoliageEditType, FString, FTableCache<FFoliageEditType>> KeyIndexHelper;

public:
    UFoliageEditKeyUniqueIndex()
        // Initialize the helper with the specific unique index name
        : KeyIndexHelper("key") {
    }

    /**
     * Finds a FoliageEdit by their unique key.
     * @param Key The key to search for.
     * @return The found FFoliageEditType, or a default-constructed FFoliageEditType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|FoliageEditIndex")
    FFoliageEditType Find(FString Key)
    {
        // Simply delegate the call to the internal helper
        return KeyIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FFoliageEditType>> InFoliageEditCache)
    {
        KeyIndexHelper.Cache = InFoliageEditCache;
    }
};
/***/

UCLASS(BlueprintType)
class ORAKAI_API UFoliageEditTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UFoliageEditKeyUniqueIndex* Key;

    UPROPERTY(BlueprintReadOnly)
    UFoliageEditChunkKeyIndex* ChunkKey;

    void PostInitialize();

    /** Update function for foliage_edit table*/
    FTableAppliedDiff<FFoliageEditType> Update(TArray<FWithBsatn<FFoliageEditType>> InsertsRef, TArray<FWithBsatn<FFoliageEditType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FFoliageEditType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFoliageEditInsert,
        const FEventContext&, Context,
        const FFoliageEditType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnFoliageEditUpdate,
        const FEventContext&, Context,
        const FFoliageEditType&, OldRow,
        const FFoliageEditType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFoliageEditDelete,
        const FEventContext&, Context,
        const FFoliageEditType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFoliageEditInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFoliageEditUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFoliageEditDelete OnDelete;

private:
    const FString TableName = TEXT("foliage_edit");

    TSharedPtr<UClientCache<FFoliageEditType>> Data;
};
