// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PlayerSessionType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PlayerSessionTable.g.generated.h"

UCLASS(Blueprintable)
class ORAKAI_API UPlayerSessionPlayerUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPlayerSessionType, FSpacetimeDBIdentity, FTableCache<FPlayerSessionType>> PlayerIndexHelper;

public:
    UPlayerSessionPlayerUniqueIndex()
        // Initialize the helper with the specific unique index name
        : PlayerIndexHelper("player") {
    }

    /**
     * Finds a PlayerSession by their unique player.
     * @param Key The player to search for.
     * @return The found FPlayerSessionType, or a default-constructed FPlayerSessionType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|PlayerSessionIndex")
    FPlayerSessionType Find(FSpacetimeDBIdentity Key)
    {
        // Simply delegate the call to the internal helper
        return PlayerIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPlayerSessionType>> InPlayerSessionCache)
    {
        PlayerIndexHelper.Cache = InPlayerSessionCache;
    }
};
/***/

UCLASS(BlueprintType)
class ORAKAI_API UPlayerSessionTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPlayerSessionPlayerUniqueIndex* Player;

    void PostInitialize();

    /** Update function for player_session table*/
    FTableAppliedDiff<FPlayerSessionType> Update(TArray<FWithBsatn<FPlayerSessionType>> InsertsRef, TArray<FWithBsatn<FPlayerSessionType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPlayerSessionType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerSessionInsert,
        const FEventContext&, Context,
        const FPlayerSessionType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPlayerSessionUpdate,
        const FEventContext&, Context,
        const FPlayerSessionType&, OldRow,
        const FPlayerSessionType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerSessionDelete,
        const FEventContext&, Context,
        const FPlayerSessionType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerSessionInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerSessionUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerSessionDelete OnDelete;

private:
    const FString TableName = TEXT("player_session");

    TSharedPtr<UClientCache<FPlayerSessionType>> Data;
};
