// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PlayerPositionType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PlayerPositionTable.g.generated.h"

UCLASS(Blueprintable)
class ORAKAI_API UPlayerPositionPlayerUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPlayerPositionType, FSpacetimeDBIdentity, FTableCache<FPlayerPositionType>> PlayerIndexHelper;

public:
    UPlayerPositionPlayerUniqueIndex()
        // Initialize the helper with the specific unique index name
        : PlayerIndexHelper("player") {
    }

    /**
     * Finds a PlayerPosition by their unique player.
     * @param Key The player to search for.
     * @return The found FPlayerPositionType, or a default-constructed FPlayerPositionType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|PlayerPositionIndex")
    FPlayerPositionType Find(FSpacetimeDBIdentity Key)
    {
        // Simply delegate the call to the internal helper
        return PlayerIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPlayerPositionType>> InPlayerPositionCache)
    {
        PlayerIndexHelper.Cache = InPlayerPositionCache;
    }
};
/***/

UCLASS(BlueprintType)
class ORAKAI_API UPlayerPositionTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPlayerPositionPlayerUniqueIndex* Player;

    void PostInitialize();

    /** Update function for player_position table*/
    FTableAppliedDiff<FPlayerPositionType> Update(TArray<FWithBsatn<FPlayerPositionType>> InsertsRef, TArray<FWithBsatn<FPlayerPositionType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPlayerPositionType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerPositionInsert,
        const FEventContext&, Context,
        const FPlayerPositionType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPlayerPositionUpdate,
        const FEventContext&, Context,
        const FPlayerPositionType&, OldRow,
        const FPlayerPositionType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerPositionDelete,
        const FEventContext&, Context,
        const FPlayerPositionType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerPositionInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerPositionUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerPositionDelete OnDelete;

private:
    const FString TableName = TEXT("player_position");

    TSharedPtr<UClientCache<FPlayerPositionType>> Data;
};
