// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/VoxelEditType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "VoxelEditTable.g.generated.h"

UCLASS(Blueprintable)
class UVoxelEditChunkKeyIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FVoxelEditType> Filter(const int64& ChunkKey) const
    {
        TArray<FVoxelEditType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<int64>>(
            OutResults,
            TEXT("ChunkKey"),
            MakeTuple(ChunkKey)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FVoxelEditType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    UFUNCTION(BlueprintCallable)
    void FilterChunkKey(TArray<FVoxelEditType>& OutResults, const int64& ChunkKey)
    {
        OutResults = Filter(ChunkKey);
    }

    TSharedPtr<FTableCache<FVoxelEditType>> LocalCache;
};

UCLASS(Blueprintable)
class ORAKAI_API UVoxelEditKeyUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FVoxelEditType, FString, FTableCache<FVoxelEditType>> KeyIndexHelper;

public:
    UVoxelEditKeyUniqueIndex()
        // Initialize the helper with the specific unique index name
        : KeyIndexHelper("key") {
    }

    /**
     * Finds a VoxelEdit by their unique key.
     * @param Key The key to search for.
     * @return The found FVoxelEditType, or a default-constructed FVoxelEditType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|VoxelEditIndex")
    FVoxelEditType Find(FString Key)
    {
        // Simply delegate the call to the internal helper
        return KeyIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FVoxelEditType>> InVoxelEditCache)
    {
        KeyIndexHelper.Cache = InVoxelEditCache;
    }
};
/***/

UCLASS(BlueprintType)
class ORAKAI_API UVoxelEditTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UVoxelEditKeyUniqueIndex* Key;

    UPROPERTY(BlueprintReadOnly)
    UVoxelEditChunkKeyIndex* ChunkKey;

    void PostInitialize();

    /** Update function for voxel_edit table*/
    FTableAppliedDiff<FVoxelEditType> Update(TArray<FWithBsatn<FVoxelEditType>> InsertsRef, TArray<FWithBsatn<FVoxelEditType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FVoxelEditType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVoxelEditInsert,
        const FEventContext&, Context,
        const FVoxelEditType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnVoxelEditUpdate,
        const FEventContext&, Context,
        const FVoxelEditType&, OldRow,
        const FVoxelEditType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVoxelEditDelete,
        const FEventContext&, Context,
        const FVoxelEditType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVoxelEditInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVoxelEditUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVoxelEditDelete OnDelete;

private:
    const FString TableName = TEXT("voxel_edit");

    TSharedPtr<UClientCache<FVoxelEditType>> Data;
};
