// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/WorldConfigType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "WorldConfigTable.g.generated.h"

UCLASS(Blueprintable)
class ORAKAI_API UWorldConfigIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FWorldConfigType, int32, FTableCache<FWorldConfigType>> IdIndexHelper;

public:
    UWorldConfigIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a WorldConfig by their unique id.
     * @param Key The id to search for.
     * @return The found FWorldConfigType, or a default-constructed FWorldConfigType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|WorldConfigIndex")
    FWorldConfigType Find(int32 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FWorldConfigType>> InWorldConfigCache)
    {
        IdIndexHelper.Cache = InWorldConfigCache;
    }
};
/***/

UCLASS(BlueprintType)
class ORAKAI_API UWorldConfigTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UWorldConfigIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for world_config table*/
    FTableAppliedDiff<FWorldConfigType> Update(TArray<FWithBsatn<FWorldConfigType>> InsertsRef, TArray<FWithBsatn<FWorldConfigType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FWorldConfigType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnWorldConfigInsert,
        const FEventContext&, Context,
        const FWorldConfigType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnWorldConfigUpdate,
        const FEventContext&, Context,
        const FWorldConfigType&, OldRow,
        const FWorldConfigType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnWorldConfigDelete,
        const FEventContext&, Context,
        const FWorldConfigType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldConfigInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldConfigUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldConfigDelete OnDelete;

private:
    const FString TableName = TEXT("world_config");

    TSharedPtr<UClientCache<FWorldConfigType>> Data;
};
