// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/FoliageEditTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UFoliageEditTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FFoliageEditType>>();

    TSharedPtr<FTableCache<FFoliageEditType>> FoliageEditTable = Data->GetOrAdd(TableName);
    FoliageEditTable->AddUniqueConstraint<FString>("key", [](const FFoliageEditType& Row) -> const FString& {
        return Row.Key; });

    Key = NewObject<UFoliageEditKeyUniqueIndex>(this);
    Key->SetCache(FoliageEditTable);

    // Register a new multi-key B-Tree index named "ChunkKey" on the FoliageEditTable.
    FoliageEditTable->AddMultiKeyBTreeIndex<TTuple<int64>>(
        TEXT("ChunkKey"),
        [](const FFoliageEditType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.ChunkKey);
        }
    );

    ChunkKey = NewObject<UFoliageEditChunkKeyIndex>(this);
    ChunkKey->SetCache(FoliageEditTable);

    /***/
}

FTableAppliedDiff<FFoliageEditType> UFoliageEditTable::Update(TArray<FWithBsatn<FFoliageEditType>> InsertsRef, TArray<FWithBsatn<FFoliageEditType>> DeletesRef)
{
    FTableAppliedDiff<FFoliageEditType> Diff = BaseUpdate<FFoliageEditType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FString>(
        [](const FFoliageEditType& Row) 
        {
            return Row.Key; 
        }
    );

    return Diff;
}

int32 UFoliageEditTable::Count() const
{
    return GetRowCountFromTable<FFoliageEditType>(Data, TableName);
}

TArray<FFoliageEditType> UFoliageEditTable::Iter() const
{
    return GetAllRowsFromTable<FFoliageEditType>(Data, TableName);
}
