// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/PlayerSessionTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UPlayerSessionTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FPlayerSessionType>>();

    TSharedPtr<FTableCache<FPlayerSessionType>> PlayerSessionTable = Data->GetOrAdd(TableName);
    PlayerSessionTable->AddUniqueConstraint<FSpacetimeDBIdentity>("player", [](const FPlayerSessionType& Row) -> const FSpacetimeDBIdentity& {
        return Row.Player; });

    Player = NewObject<UPlayerSessionPlayerUniqueIndex>(this);
    Player->SetCache(PlayerSessionTable);

    /***/
}

FTableAppliedDiff<FPlayerSessionType> UPlayerSessionTable::Update(TArray<FWithBsatn<FPlayerSessionType>> InsertsRef, TArray<FWithBsatn<FPlayerSessionType>> DeletesRef)
{
    FTableAppliedDiff<FPlayerSessionType> Diff = BaseUpdate<FPlayerSessionType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FSpacetimeDBIdentity>(
        [](const FPlayerSessionType& Row) 
        {
            return Row.Player; 
        }
    );

    return Diff;
}

int32 UPlayerSessionTable::Count() const
{
    return GetRowCountFromTable<FPlayerSessionType>(Data, TableName);
}

TArray<FPlayerSessionType> UPlayerSessionTable::Iter() const
{
    return GetAllRowsFromTable<FPlayerSessionType>(Data, TableName);
}
