// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/PlayerPositionTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UPlayerPositionTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FPlayerPositionType>>();

    TSharedPtr<FTableCache<FPlayerPositionType>> PlayerPositionTable = Data->GetOrAdd(TableName);
    PlayerPositionTable->AddUniqueConstraint<FSpacetimeDBIdentity>("player", [](const FPlayerPositionType& Row) -> const FSpacetimeDBIdentity& {
        return Row.Player; });

    Player = NewObject<UPlayerPositionPlayerUniqueIndex>(this);
    Player->SetCache(PlayerPositionTable);

    /***/
}

FTableAppliedDiff<FPlayerPositionType> UPlayerPositionTable::Update(TArray<FWithBsatn<FPlayerPositionType>> InsertsRef, TArray<FWithBsatn<FPlayerPositionType>> DeletesRef)
{
    FTableAppliedDiff<FPlayerPositionType> Diff = BaseUpdate<FPlayerPositionType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FSpacetimeDBIdentity>(
        [](const FPlayerPositionType& Row) 
        {
            return Row.Player; 
        }
    );

    return Diff;
}

int32 UPlayerPositionTable::Count() const
{
    return GetRowCountFromTable<FPlayerPositionType>(Data, TableName);
}

TArray<FPlayerPositionType> UPlayerPositionTable::Iter() const
{
    return GetAllRowsFromTable<FPlayerPositionType>(Data, TableName);
}
