// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/VoxelEditTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UVoxelEditTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FVoxelEditType>>();

    TSharedPtr<FTableCache<FVoxelEditType>> VoxelEditTable = Data->GetOrAdd(TableName);
    VoxelEditTable->AddUniqueConstraint<FString>("key", [](const FVoxelEditType& Row) -> const FString& {
        return Row.Key; });

    Key = NewObject<UVoxelEditKeyUniqueIndex>(this);
    Key->SetCache(VoxelEditTable);

    // Register a new multi-key B-Tree index named "ChunkKey" on the VoxelEditTable.
    VoxelEditTable->AddMultiKeyBTreeIndex<TTuple<int64>>(
        TEXT("ChunkKey"),
        [](const FVoxelEditType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.ChunkKey);
        }
    );

    ChunkKey = NewObject<UVoxelEditChunkKeyIndex>(this);
    ChunkKey->SetCache(VoxelEditTable);

    /***/
}

FTableAppliedDiff<FVoxelEditType> UVoxelEditTable::Update(TArray<FWithBsatn<FVoxelEditType>> InsertsRef, TArray<FWithBsatn<FVoxelEditType>> DeletesRef)
{
    FTableAppliedDiff<FVoxelEditType> Diff = BaseUpdate<FVoxelEditType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FString>(
        [](const FVoxelEditType& Row) 
        {
            return Row.Key; 
        }
    );

    return Diff;
}

int32 UVoxelEditTable::Count() const
{
    return GetRowCountFromTable<FVoxelEditType>(Data, TableName);
}

TArray<FVoxelEditType> UVoxelEditTable::Iter() const
{
    return GetAllRowsFromTable<FVoxelEditType>(Data, TableName);
}
