// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/WorldConfigTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UWorldConfigTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FWorldConfigType>>();

    TSharedPtr<FTableCache<FWorldConfigType>> WorldConfigTable = Data->GetOrAdd(TableName);
    WorldConfigTable->AddUniqueConstraint<int32>("id", [](const FWorldConfigType& Row) -> const int32& {
        return Row.Id; });

    Id = NewObject<UWorldConfigIdUniqueIndex>(this);
    Id->SetCache(WorldConfigTable);

    /***/
}

FTableAppliedDiff<FWorldConfigType> UWorldConfigTable::Update(TArray<FWithBsatn<FWorldConfigType>> InsertsRef, TArray<FWithBsatn<FWorldConfigType>> DeletesRef)
{
    FTableAppliedDiff<FWorldConfigType> Diff = BaseUpdate<FWorldConfigType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<int32>(
        [](const FWorldConfigType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UWorldConfigTable::Count() const
{
    return GetRowCountFromTable<FWorldConfigType>(Data, TableName);
}

TArray<FWorldConfigType> UWorldConfigTable::Iter() const
{
    return GetAllRowsFromTable<FWorldConfigType>(Data, TableName);
}
