// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ApplyVoxelEdit.g.generated.h"

// Reducer arguments struct for ApplyVoxelEdit
USTRUCT(BlueprintType)
struct ORAKAI_API FApplyVoxelEditArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkZ = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalZ = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 MaterialId = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    bool IsWater = false;

    FApplyVoxelEditArgs() = default;

    FApplyVoxelEditArgs(const int32& InChunkX, const int32& InChunkY, const int32& InChunkZ, const int32& InLocalX, const int32& InLocalY, const int32& InLocalZ, const int32& InMaterialId, const bool& InIsWater)
        : ChunkX(InChunkX), ChunkY(InChunkY), ChunkZ(InChunkZ), LocalX(InLocalX), LocalY(InLocalY), LocalZ(InLocalZ), MaterialId(InMaterialId), IsWater(InIsWater)
    {}


    FORCEINLINE bool operator==(const FApplyVoxelEditArgs& Other) const
    {
        return ChunkX == Other.ChunkX && ChunkY == Other.ChunkY && ChunkZ == Other.ChunkZ && LocalX == Other.LocalX && LocalY == Other.LocalY && LocalZ == Other.LocalZ && MaterialId == Other.MaterialId && IsWater == Other.IsWater;
    }
    FORCEINLINE bool operator!=(const FApplyVoxelEditArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FApplyVoxelEditArgs, ChunkX, ChunkY, ChunkZ, LocalX, LocalY, LocalZ, MaterialId, IsWater);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API UApplyVoxelEditReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkZ = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalZ = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 MaterialId = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    bool IsWater = false;

};


