// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ApplyFoliageEdit.g.generated.h"

// Reducer arguments struct for ApplyFoliageEdit
USTRUCT(BlueprintType)
struct ORAKAI_API FApplyFoliageEditArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldZ = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    bool Removed = false;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 TypeId = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float Yaw = 0.0f;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float Scale = 0.0f;

    FApplyFoliageEditArgs() = default;

    FApplyFoliageEditArgs(const int32& InWorldX, const int32& InWorldY, const int32& InWorldZ, const bool& InRemoved, const int32& InTypeId, const float& InYaw, const float& InScale)
        : WorldX(InWorldX), WorldY(InWorldY), WorldZ(InWorldZ), Removed(InRemoved), TypeId(InTypeId), Yaw(InYaw), Scale(InScale)
    {}


    FORCEINLINE bool operator==(const FApplyFoliageEditArgs& Other) const
    {
        return WorldX == Other.WorldX && WorldY == Other.WorldY && WorldZ == Other.WorldZ && Removed == Other.Removed && TypeId == Other.TypeId && Yaw == Other.Yaw && Scale == Other.Scale;
    }
    FORCEINLINE bool operator!=(const FApplyFoliageEditArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FApplyFoliageEditArgs, WorldX, WorldY, WorldZ, Removed, TypeId, Yaw, Scale);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API UApplyFoliageEditReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldZ = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    bool Removed = false;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 TypeId = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float Yaw = 0.0f;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float Scale = 0.0f;

};


