// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ClearFoliageEdit.g.generated.h"

// Reducer arguments struct for ClearFoliageEdit
USTRUCT(BlueprintType)
struct ORAKAI_API FClearFoliageEditArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 WorldZ = 0;

    FClearFoliageEditArgs() = default;

    FClearFoliageEditArgs(const int32& InWorldX, const int32& InWorldY, const int32& InWorldZ)
        : WorldX(InWorldX), WorldY(InWorldY), WorldZ(InWorldZ)
    {}


    FORCEINLINE bool operator==(const FClearFoliageEditArgs& Other) const
    {
        return WorldX == Other.WorldX && WorldY == Other.WorldY && WorldZ == Other.WorldZ;
    }
    FORCEINLINE bool operator!=(const FClearFoliageEditArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FClearFoliageEditArgs, WorldX, WorldY, WorldZ);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API UClearFoliageEditReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 WorldZ = 0;

};


