// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ClearVoxelEdit.g.generated.h"

// Reducer arguments struct for ClearVoxelEdit
USTRUCT(BlueprintType)
struct ORAKAI_API FClearVoxelEditArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 ChunkZ = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalX = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalY = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 LocalZ = 0;

    FClearVoxelEditArgs() = default;

    FClearVoxelEditArgs(const int32& InChunkX, const int32& InChunkY, const int32& InChunkZ, const int32& InLocalX, const int32& InLocalY, const int32& InLocalZ)
        : ChunkX(InChunkX), ChunkY(InChunkY), ChunkZ(InChunkZ), LocalX(InLocalX), LocalY(InLocalY), LocalZ(InLocalZ)
    {}


    FORCEINLINE bool operator==(const FClearVoxelEditArgs& Other) const
    {
        return ChunkX == Other.ChunkX && ChunkY == Other.ChunkY && ChunkZ == Other.ChunkZ && LocalX == Other.LocalX && LocalY == Other.LocalY && LocalZ == Other.LocalZ;
    }
    FORCEINLINE bool operator!=(const FClearVoxelEditArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FClearVoxelEditArgs, ChunkX, ChunkY, ChunkZ, LocalX, LocalY, LocalZ);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API UClearVoxelEditReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 ChunkZ = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalX = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalY = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 LocalZ = 0;

};


