// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "SetWorldConfig.g.generated.h"

// Reducer arguments struct for SetWorldConfig
USTRUCT(BlueprintType)
struct ORAKAI_API FSetWorldConfigArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int64 WorldSeed = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 GenerationVersion = 0;

    FSetWorldConfigArgs() = default;

    FSetWorldConfigArgs(const int64& InWorldSeed, const uint32& InGenerationVersion)
        : WorldSeed(InWorldSeed), GenerationVersion(InGenerationVersion)
    {}


    FORCEINLINE bool operator==(const FSetWorldConfigArgs& Other) const
    {
        return WorldSeed == Other.WorldSeed && GenerationVersion == Other.GenerationVersion;
    }
    FORCEINLINE bool operator!=(const FSetWorldConfigArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FSetWorldConfigArgs, WorldSeed, GenerationVersion);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API USetWorldConfigReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int64 WorldSeed = 0;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 GenerationVersion = 0;

};


