// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "UpdatePlayerPosition.g.generated.h"

// Reducer arguments struct for UpdatePlayerPosition
USTRUCT(BlueprintType)
struct ORAKAI_API FUpdatePlayerPositionArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double X = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Y = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Z = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float Yaw = 0.0f;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float Pitch = 0.0f;

    FUpdatePlayerPositionArgs() = default;

    FUpdatePlayerPositionArgs(const double& InX, const double& InY, const double& InZ, const float& InYaw, const float& InPitch)
        : X(InX), Y(InY), Z(InZ), Yaw(InYaw), Pitch(InPitch)
    {}


    FORCEINLINE bool operator==(const FUpdatePlayerPositionArgs& Other) const
    {
        return X == Other.X && Y == Other.Y && Z == Other.Z && Yaw == Other.Yaw && Pitch == Other.Pitch;
    }
    FORCEINLINE bool operator!=(const FUpdatePlayerPositionArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FUpdatePlayerPositionArgs, X, Y, Z, Yaw, Pitch);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ORAKAI_API UUpdatePlayerPositionReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double X = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Y = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Z = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float Yaw = 0.0f;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float Pitch = 0.0f;

};


